### ISSUE TITLE
#cloudformationoutput

### ISSUE THREAD

**Issue by gdestuynder** [nubisproject/nubis-ci#105]
# From Risk record
Addition of CloudFormation stack output into Consul is manual

Recommendation:
Create a programmatic method of having jenkins query for the stack output and inject the result into consul

# From Nubis team mitigations
Jenkin's has always taken cloudformation output and put into consule

**Comment by gdestuynder** [comment]
@gozer @tinnightcap 
Do you have a pointer to the script that does the copy from cloudformation to consul?

**Comment by tinnightcap** [comment]
@gdestuynder https://github.com/Nubisproject/nubis-builder/blob/master/bin/nubis-consul#L214

**Comment by gdestuynder** [comment]
Thanks!
@tinnightcap I see a lot of calls to curl with '--insecure' (ignores certificate validation on https) even thus URLs are forced to https, for ex https://github.com/Nubisproject/nubis-builder/blob/master/bin/nubis-consul#L100 (there's more just grep for '--insecure' or '-k').

This uses the URL constructed with the domain taken from $CONSUL_ENDPOINT.
I suspect that we do want to have certificate validate/proper https here. Is there a reason for not validating the certificate? (for ex: "its always localhost" or "we decide to trust the VPC network" etc.)
That said in general I would argue against disabling certificate validation since this leads to confusion when changes are made

**Comment by tinnightcap** [comment]
@gdestuynder the consul endpoint in always within the VPC. I think we trust this in general and it should not be an issue. Having said that, the reason for the --insecure option is that we do not have official  certificates for all of the consul clusters and so these commands simply fail without that flag.

**Comment by gozer** [comment]
what @jd said++

**Comment by jeffbryner** [comment]
If this is working, then close this issue and lets open a different one for the --insecure root issue (ssl self-signed certs) to discuss

**Comment by jd** [comment]
I said nothing.

**Comment by gdestuynder** [comment]
Split this in https://github.com/nubisproject/nubis-ci/issues/118 - I think this one (105) can be closed.

**Comment by tinnightcap** [comment]
closing as per consensus
