### ISSUE TITLE
#jenkinsiamrole

### ISSUE THREAD

**Issue by gdestuynder** [nubisproject/nubis-ci#106]
# From Risk Record
Enumerate
 the specific permissions that Jenkins needs to create stacks and create
 an IAM role with only those permissions for jenkins to use

# From Nubis team mitigations
Reduced by one account per application

**Comment by gdestuynder** [comment]
@gozer @tinnightcap do you have a pointer/link to the permissions settings?

**Comment by gozer** [comment]
https://github.com/Nubisproject/nubis-ci/blob/master/nubis/terraform/main.tf#L229

**Comment by gene1wood** [comment]
Looks good, thanks for the jenkins policies 

https://github.com/Nubisproject/nubis-ci/blob/master/nubis/terraform/main.tf#L172-L343

**Comment by gdestuynder** [comment]
see also https://github.com/Nubisproject/nubis-ci/blob/master/nubis/terraform/main.tf#L320 for #productjenkinscreateiamroles (separate risk)

**Comment by tinnightcap** [comment]
this is a dup of https://github.com/Nubisproject/nubis-ci/issues/83
