### ISSUE TITLE
Validate Consul certs

### ISSUE THREAD

**Issue by gdestuynder** [nubisproject/nubis-ci#118]
See also https://github.com/Nubisproject/nubis-ci/issues/105#issuecomment-143039752

Splitting this issue as this only concerns the use of --insecure and -k when calling curl to talk with Consul.
Consul is only reached from within the VPC which reduces the chances of a MITM - however an instance could still potentially MITM another in the same VPC - thus ideally it would be good to validate the certificates properly, and hence why I'm opening this issue (separate tracking from issue 105).
# Please explain the issue. The first line will become the title. Trailing

**Comment by gozer** [comment]
Let's also not forget that the endpoint is constructed by the CI system, the only actor that does non-local Consul access.

To MiTM this, one would need to subvert Route53

**Comment by tinnightcap** [comment]
@gdestuynder @gene1wood Can you provide a link to this in the RRA? I need to know the risk level for prioritizing work. - Thanks

**Comment by tinnightcap** [comment]
The only time we talk to consul over http is:

 1 During node bootstrap to get consul secret (going away once we implement KMS in https://github.com/Nubisproject/nubis-consul/issues/63)
 2  Once the ci system is done updating or creating a stack it publishes stack outputs to consul. This post is done with a known generated name. This name is looked up in Route53. In order for an attacker to MITM this request they would first need to subvert Route 53 and then establish an https endpoint to mimic consul with a self signed cert.

The suggested solution is to provide the default cert (the one used by consul) to be used by curl (on the ci system) for cert pinning.

**Comment by gene1wood** [comment]
The risk called out in this issue of a MITM attack against consul is not represented in the RRA so there is no risk ID to link to.

**Comment by gozer** [comment]
We have been for a while now retrieving the Consul CA cert from unicreds/dynamodb/kms and use it for all http trafic to Consul's http endpoint like so:

```bash
curl --retry 10 -fs --cacert /etc/consul/ca.pem
```

So curl -k is long gone.
