### ISSUE TITLE
Generate /opt/nubis-builder/secrets/variables.json

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-ci#39]
Most of what we need is in Consul/user-data already.

Only issue is the X509 certificates, but I believe these can be generated.

**Comment by bhourigan** [comment]
I think that the certificates can be deprecated in favor of an IAM role that the build instance can assume.

**Comment by gozer** [comment]
Unfortunately, it's a strange requirements of s3 based AMIs, a signing certificate is necessary...

What I am hoping is that we can generate that self-signed cert on each CI system. It doens't look like the certificate needs to be known to Amazon, just *a* cert.
