### ISSUE TITLE
Set packer option -color=false or colorize output

### ISSUE THREAD

**Issue by tinnightcap** [nubisproject/nubis-ci#405]
When reviewing the Jenkins build log containing packer outpu (through nubis-bulder) the color control characters make the output difficult to read. Suggest either passing in the packer option -color=false or see if Jenkins can display colorized output. Perhaps something like https://wiki.jenkins-ci.org/display/JENKINS/AnsiColor+Plugin

**Comment by gozer** [comment]
Required job XML config
```xml 
 </publishers>
  <buildWrappers>
    <hudson.plugins.ansicolor.AnsiColorBuildWrapper plugin="ansicolor@0.5.0">
      <colorMapName>xterm</colorMapName>
    </hudson.plugins.ansicolor.AnsiColorBuildWrapper>
  </buildWrappers>
</project>
```
