### ISSUE TITLE
#productjenkinscreateiamroles - Product developers have the ability to gain full control of the product account

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-ci#80]
From https://mana.mozilla.org/wiki/display/SECURITY/Nubis#Nubis-#jenkinscreateiamroles

Jenkins can create any IAM role

If each product/project's jenkins build system is assigned an IAM role which contains the iam:CreateRole permission, then all jenkins boxes could create arbitrary IAM roles, with permissions like *:* granting them rights to create and modify all production resources for all products/projects. By extension, all developers who have rights to commit code to any nubis based product would consequently be able to create and modify all production resources for all products/projects. This results in the situation where any developers compromised account or any bad-actor developer could negatively impact every product hosted in nubis.

Another specific example is that a compromised developer account or bad-actor developer for Product A could create an IAM role with permissions to kms:Decrypt and decrypt all production secrets for Product B.

Recommendations :

- Do not grant iam:CreateRole to jenkins boxes and require all IAM role creation to be done out of band by another system (or jenkins box) for which the only users with commit rights are users who already have *:* permissions. This violates the Mozilla Nubis architecture pinciples "Self-Service" principle.
- Configure jenkins to parse the CloudFormation document, look for IAM Roles, and query AWS to determine if they already exist in the environment. If they do not exist or exist but this CloudFormation template will change them, then have jenkins determine what commit resulted in the change, then look for a comment in the PR of the commit that creates the new IAM role. This comment in the PR would need to come from a defined set of global nubis reviewers and be in a well-known format indicating approval of the new IAM role. Without this approval comment, jenkins would refuse to deploy. This solution requires the establishment of a community of approvers who's job is to protect the nubis environment by reviewing new IAM roles and IAM role changes in the various products which live in nubis.
- Configure jenkins to parse the CloudFormation document and look for the presence of IAM roles which grant permissions that could affect other products. This approach would require a sophisticated model to differentiate AWS resources for each product. This can be accomplished with ec2-tags with conditionals and ARN paths with resource strings, however it may not be possible to enable granular differentiated control for all AWS resources. This would also require that nubis administrators monitor for new AWS capabilities since these new capabilities, when released by Amazon, would by default not be present in this tools logic and would be allowed by default, constituting a security risk. Some examples of what this logic might look like are
- Look for permissions to affect ec2 instances where the permission is not constrained by policy conditions requiring that the ec2 instance to be affected must be tagged with a given "Owner" tag
- Look for the kms:Decrypt permission which by nubis policy would be prohibited to all

**Comment by gozer** [comment]
In one account per app, the Jenkins instance can only affect the account it's operating under.

Therefore, to use the example stated, a compromised developer account or bad-actor developer for product A couldn't trick Jenkins into creating an IAM role that gives it access to product B or its secrets.

**Comment by gene1wood** [comment]
This issue was marked in the Risk Record as review needed. @gozer , can you add to this ticket what was implemented so we can review it?

**Comment by RichardWeiss** [comment]
This issue is tagged as wontfix. Does this mean that it won't be fixed before deployment, or not at all?

**Comment by tinnightcap** [comment]
The title of this issue changed in the tracking sheet. The RRA sheet links to this issue for this risk, I am updating to reflect that change.

**Comment by tinnightcap** [comment]
A lambda function will be created that creates the necessary IAM roles. The capability to create IAM roles will be removed from Jenkins. Jenkins will not have access to update lambda functions.

**Comment by tinnightcap** [comment]
We have decided to accept this risk. Additional monitoring is being put in place in coordination with InfoSec. This work is being tracked elsewhere.
