### ISSUE TITLE
#productjenkinscreateiamroles - Product developers have the ability to gain full control of the product account

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-ci#81]
From https://mana.mozilla.org/wiki/display/SECURITY/Nubis#Nubis-#jenkinspassrole

Jenkins can apply any IAM role to an instance

Every product's jenkins box has *:* permissions over * resources as mentioned in #jenkinsiamrole. As a result each product's jenkins box has an unrestricted iam:PassRole permission granting it the ability to apply any IAM role to an ec2 instance. This results in the jenkins box for Product A being able to create ec2 instances with IAM Roles intended for use with Product B. As a consequence any compromised developer github account or bad-actor developer could act with the permissions of any and all products IAM Roles. If we were to use KMS to distribute secrets this would mean all developers could read production secrets for all products (not just their own).

Recommendations :

- Establish a policy of using ARN paths for IAM Roles. Grant each jenkins box the iam:PassRole permission only for resources that begin with the ARN path specific to that jenkins box's product. If a developer creates a CloudFormation template which creates an ec2 instance with an IAM Role of a different product, jenkins will not have permissions to apply that foreign role to the ec2 instance.

**Comment by gozer** [comment]
In one account per app, Jenkins can only affect the resource in the account it's running, limited to that one single application.

Therefore, the Jenkins box for Product A has no ability whatsoever to affect the AWS account of Product B.

**Comment by tinnightcap** [comment]
This was considered deprecated by one account per app, however security opened a new issue with the exact same risk, I will therefore modify this issue with the updated language.

**Comment by tinnightcap** [comment]
If each product/project's jenkins build system is assigned an IAM role which contains the iam:CreateRole permission, then each jenkins box could create arbitrary IAM roles, with permissions like *:* granting them rights to create and modify all production resources for the product in their AWS account. By extension, all developers who have rights to commit code to a nubis based product are able to create and modify all production resources for that product. This results in the situation where a developer's compromised account or a bad-actor developer could negatively impact the product for which they have github commit rights.

The result of this is that all developers with Github commit rights to repositories that nubis jenkins instances consume have the ability to gain full control of the product account in which that jenkins instance is hosted. Without this specific ability, developers would only have the ability to modify the product stack, and create new resources, but not modify infrastructure in the account (e.g. fluentd log aggregator, consul, jenkins)

**Comment by tinnightcap** [comment]
I believe this is a duplicate of issue #80. I am closing this one in favor of that one.
