### ISSUE TITLE
Jenkins permissions are broad permissions

### ISSUE THREAD

**Issue by gozer** [nubisproject/nubis-ci#83]
From https://mana.mozilla.org/wiki/display/SECURITY/Nubis#Nubis-#jenkinsiamrole

Jenkins permissions are broad permissions

The jenkins instance is granted *:* permissions. This permission set is broader than what the instance needs to be able to build CloudFormation stacks. Compromise of this machine would have a greater impact due to these unneeded privileges.

Risk level Rationale :

The single jenkins box for all products increases risk for everything else (for example a problem with wiki.mozilla.org could affect releng). The overly broad permissions merely enabling an attacker to create resources in an unused region is less significant.

Recommendations :

Enumerate the specific permissions that Jenkins needs to create stacks and create an IAM role with only those permissions for jenkins to use

**Comment by gene1wood** [comment]
These are the current permissions

    https://github.com/Nubisproject/nubis-meta/blob/679c3faddc575054ade4144e6d9030cc5df10851/meta.json#L488-L533
    https://github.com/Nubisproject/nubis-meta/blob/679c3faddc575054ade4144e6d9030cc5df10851/meta.json#L534-L598
    https://github.com/Nubisproject/nubis-meta/blob/679c3faddc575054ade4144e6d9030cc5df10851/meta.json#L599-L625

**Comment by tinnightcap** [comment]
Duplicated and closed in
https://github.com/nubisproject/nubis-ci/issues/106
